### ISSUE TITLE
不能hook静态方法和final 类,有办法解决么

### ISSUE THREAD

**Issue by liupeng110** [asLody/legend#25]
不能hook静态方法和final 类,有办法解决么

**Comment by txy0110** [comment]
也想知道不能hook静态方法怎么办？

**Comment by liupeng110** [comment]
@txy0110   我已经更换框架,用xposed。

**Comment by txy0110** [comment]
可是我想在包体内使用，使用场景是某加固软件加固后的apk，dex是隐藏加载的，但是用dumpdex可以把dex dump出来，可是想用java hook的方式去除掉源dex中被植入的java检测代码

**Comment by liupeng110** [comment]
没什么好的办法   你找到办法也告诉我下

**Comment by txy0110** [comment]
我试图直接用adbi hook DexFile的openDexFileNative方法，直接替换掉dex加载的文件，可是不知道为什么地址是对的，输出来的原指令都是对的，似乎在调到oepnDexFileNative的时候崩溃了。。。原因不详~~

**Comment by txy0110** [comment]
https://github.com/asLody/whale作者的这个仓库不知道有没有用

**Comment by liupeng110** [comment]
有用，可以hook静态的。
